"""PEP 517 backend that generates, validates, and then removes build payloads."""

import contextlib
import hashlib
import json
import os
import shutil
import subprocess
import time
from pathlib import Path

from setuptools import build_meta as _setuptools

from .inventory import (
    GENERATED_LOCAL_INVENTORY,
    IDENTITY_INPUTS,
    LICENSE_EXPRESSION,
    PACKAGE_VERSION,
    SOURCE_INVENTORY,
    UPSTREAM_URL,
)

ROOT = Path(__file__).resolve().parent.parent
PAYLOAD = ROOT / "cli" / "omama_cli" / "_payload"
IDENTITY_FILE = ROOT / "_build_identity.json"


def _sha256(data):
    return hashlib.sha256(data).hexdigest()


BUILD_LOCK = ROOT / ".omama-build.lock"


def _git(*args):
    command = ["git", "-c", "safe.directory=" + ROOT.as_posix()] + list(args)
    result = subprocess.run(command, cwd=str(ROOT), stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    return result.stdout.strip() if result.returncode == 0 else None


def _git_owns_source_root():
    """True only when Git's top level is this source root.

    Git searches upwards, so building from a source tree that merely sits
    inside some other repository -- an extracted archive, a vendored copy --
    otherwise reports that unrelated repository's HEAD as Omama's own clean
    revision.  A revision is claimed only when Git is describing this tree.
    """
    toplevel = _git("rev-parse", "--show-toplevel")
    if not toplevel:
        return False
    try:
        return Path(toplevel).resolve() == ROOT.resolve()
    except OSError:
        return False


def _identity_inputs_digest():
    digest = hashlib.sha256()
    for relative in sorted(IDENTITY_INPUTS):
        path = ROOT / relative
        if not path.is_file():
            raise RuntimeError("missing authoritative identity input: " + relative)
        data = path.read_bytes()
        digest.update(relative.encode("utf-8") + b"\0" + _sha256(data).encode("ascii") + b"\n")
    return digest.hexdigest()


def _identity():
    inputs_digest = _identity_inputs_digest()
    if IDENTITY_FILE.is_file():
        value = json.loads(IDENTITY_FILE.read_text(encoding="utf-8"))
        if value.get("schema") == 1 and value.get("identity_inputs_digest") == inputs_digest:
            return value
        if value.get("schema") == 1 and value.get("revision"):
            value.update({
                "dirty": True,
                "exact_revision": None,
                "dirty_digest": inputs_digest,
                "identity_inputs_digest": inputs_digest,
                "modified_after_identity_capture": True,
            })
            return value
    if _git_owns_source_root():
        revision = _git("rev-parse", "HEAD") or "unknown"
        status = _git("status", "--porcelain=v1", "--untracked-files=all")
        dirty = status is None or bool(status)
    else:
        # Not a Git checkout of this project: the revision is unavailable, and
        # an enclosing repository's revision is never borrowed.
        revision = "unknown"
        dirty = True
    return {
        "schema": 1,
        "url": UPSTREAM_URL,
        "revision": revision,
        "dirty": dirty,
        "exact_revision": None if dirty or revision == "unknown" else revision,
        "dirty_digest": inputs_digest if dirty else None,
        "identity_inputs_digest": inputs_digest,
        "modified_after_identity_capture": False,
        "dirty_digest_policy": "sha256 of sorted authoritative identity-input path and content-sha256 pairs",
    }


def _provenance(source):
    exact = source["exact_revision"] or "none (dirty or unavailable source tree)"
    dirty_digest = source["dirty_digest"] or "none (clean source tree)"
    return (
        "# Omama packaged bundle provenance\n\n"
        "- Upstream source: {url}\n"
        "- Source revision: `{revision}`\n"
        "- Dirty source: `{dirty}`\n"
        "- Exact clean revision: `{exact}`\n"
        "- Dirty digest: `{dirty_digest}`\n"
        "- Identity inputs digest: `{inputs_digest}`\n"
        "- Modified after identity capture: `{modified}`\n"
        "- Dirty digest policy: {policy}\n"
        "- Package version: `{version}`\n"
        "- License: `{license}`; copied as `tools/omama/LICENSE`\n"
        "- Generated by: `build_backend.backend`; do not hand-edit generated payload output.\n"
    ).format(
        url=source["url"], revision=source["revision"], dirty=str(source["dirty"]).lower(),
        exact=exact, dirty_digest=dirty_digest, policy=source["dirty_digest_policy"],
        inputs_digest=source["identity_inputs_digest"], modified=str(source["modified_after_identity_capture"]).lower(),
        version=PACKAGE_VERSION, license=LICENSE_EXPRESSION,
    ).encode("utf-8")


def _generate_payload():
    source = _identity()
    if PAYLOAD.exists():
        shutil.rmtree(str(PAYLOAD))
    files_root = PAYLOAD / "files"
    entries = []
    for source_path, destination, ownership in SOURCE_INVENTORY:
        data = (ROOT / source_path).read_bytes()
        # Package-data discovery skips dot-directories. Resource storage is an
        # internal name; the manifest retains the exact dot-prefixed destination.
        resource = "files/" + destination.lstrip(".")
        target = PAYLOAD / resource
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        entries.append({
            "source": source_path,
            "destination": destination,
            "resource": resource,
            "ownership": ownership,
            "sha256": _sha256(data),
            "size": len(data),
        })
    provenance = _provenance(source)
    provenance_destination = "tools/omama/PROVENANCE.md"
    provenance_resource = "files/" + provenance_destination
    target = PAYLOAD / provenance_resource
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(provenance)
    entries.append({
        "source": None,
        "generated_by": "build_backend.backend",
        "destination": provenance_destination,
        "resource": provenance_resource,
        "ownership": "immutable",
        "sha256": _sha256(provenance),
        "size": len(provenance),
    })
    entries.sort(key=lambda item: item["destination"])
    license_identity = {"expression": LICENSE_EXPRESSION, "destination": "tools/omama/LICENSE"}
    ownership_policy = {
        "immutable": "same bundle requires exact hash; drift is a conflict",
        "editable-bootstrap": "create once; preserve all existing team bytes after adoption",
        "generated-wiring": "T7 owns generation and conflict-safe activation",
        "unowned": "adopt only when byte-identical to this validated bundle",
        "package-update": "a different bundle id is an update decision, never implicit repair",
    }
    generated_local = list(GENERATED_LOCAL_INVENTORY)
    identity_basis = {
        "package_version": PACKAGE_VERSION,
        "source": source,
        "license": license_identity,
        "files": [{k: entry[k] for k in ("destination", "ownership", "sha256")} for entry in entries],
        "generated_local": generated_local,
        "ownership_policy": ownership_policy,
    }
    bundle_id = _sha256(json.dumps(identity_basis, sort_keys=True, separators=(",", ":")).encode("utf-8"))
    manifest = {
        "schema": 1,
        "package_version": PACKAGE_VERSION,
        "bundle_id": bundle_id,
        "source": source,
        "license": license_identity,
        "files": entries,
        "required_destinations": [entry["destination"] for entry in entries],
        "generated_local": generated_local,
        "installed_identity": {
            "destination": "tools/omama/manifest.json",
            "resource": "manifest.json",
            "ownership": "immutable-generated",
            "hash_policy": "self hash is recorded in local installation state by T5; bundle_id binds manifest semantics",
        },
        "ownership_policy": ownership_policy,
    }
    PAYLOAD.mkdir(parents=True, exist_ok=True)
    with (PAYLOAD / "manifest.json").open("w", encoding="utf-8", newline="\n") as stream:
        stream.write(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    return source


def _cleanup_payload():
    if PAYLOAD.exists():
        shutil.rmtree(str(PAYLOAD))


def _discard_stale_build_output():
    """Remove this project's own setuptools staging before generating anew.

    setuptools copies package files into ``build/lib`` and never removes files
    that have since disappeared from the source, so a payload entry deleted or
    renamed between builds would otherwise be carried into the next wheel.
    Only this project's own gitignored build directory is removed, and only
    while the build lock is held.
    """
    build_root = ROOT / "build"
    if build_root.is_dir() and not build_root.is_symlink():
        shutil.rmtree(str(build_root))


@contextlib.contextmanager
def _build_lock():
    """Serialize payload generation and staging within one source tree.

    Payload generation writes to a fixed location inside the package, so two
    overlapping builds of the same checkout would otherwise interleave their
    generation and cleanup.  The lock makes them sequential; neither observes
    the other's partial state, and the source tree is unchanged afterwards.
    """
    deadline = time.monotonic() + 600
    while True:
        try:
            descriptor = os.open(str(BUILD_LOCK), os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
            break
        except FileExistsError:
            if time.monotonic() > deadline:
                raise RuntimeError(
                    "another build of this source tree has held {0} for more than 600s; "
                    "remove it only after confirming no build is running".format(BUILD_LOCK))
            time.sleep(0.05)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            stream.write(json.dumps({"pid": os.getpid()}) + "\n")
        yield
    finally:
        try:
            os.unlink(str(BUILD_LOCK))
        except FileNotFoundError:
            pass


def build_wheel(wheel_directory, config_settings=None, metadata_directory=None):
    with _build_lock():
        _discard_stale_build_output()
        _generate_payload()
        try:
            return _setuptools.build_wheel(wheel_directory, config_settings, metadata_directory)
        finally:
            _cleanup_payload()


def build_sdist(sdist_directory, config_settings=None):
    # Phase-1 delivery is wheel-only.  No sdist is produced and no wheel/sdist
    # equivalence is claimed; whether a public release requires a source
    # distribution is a separate, later decision.
    raise RuntimeError(
        "phase-1 Omama delivery is wheel-only: no source distribution is built, and no "
        "wheel-to-sdist equivalence is claimed. Build the wheel instead."
    )


def prepare_metadata_for_build_wheel(metadata_directory, config_settings=None):
    return _setuptools.prepare_metadata_for_build_wheel(metadata_directory, config_settings)


def get_requires_for_build_wheel(config_settings=None):
    return _setuptools.get_requires_for_build_wheel(config_settings)


def get_requires_for_build_sdist(config_settings=None):
    return _setuptools.get_requires_for_build_sdist(config_settings)
